$('h1').css('color', 'blue')
$('body').css('background-color', 'red')
$('#everything').css('font-size', '300%')
$('.holder').css('border-color', 'black')
$('.holder').css('border-style', 'solid')
$('ul').css('font-weight', 'bold')
$('h1>p').css('color', 'green')
$('#secret').css('display', 'block')
$('#change-me').html('new version')
$('#change-me').append('<br>'+'new version2')
$('#change-me').html('new version3 <p> nouveau </p> new version4')
$('#change-me').append('<br>'+'new version5 <p> nouveau2 </p> new version6')
$('ul li').html('cool1')
$('ul li').append('<br>' + 'coolbean')
$('#everything').prepend('<ul> <li> one </li> <li> two </li> <li> three </li> </ul>')
